#!/usr/bin/env python3
"""ProInsights — static SEO site builder.

Generates all SEO pages from a shared template + JSON content files.
No build framework — pure stdlib Python. Output is plain HTML that
Cloudflare Pages serves as-is.

Usage:
    python build_seo_site.py            # build all pages
    python build_seo_site.py --check    # validate content files, don't write

Files this writes (relative to this script's directory):
  - {slug}.html                                  (commercial pages)
  - cyprus/{slug}.html                           (Cyprus local pages)
  - blog/index.html                              (blog index)
  - blog/{slug}.html                             (blog articles)
  - sitemap.xml                                  (regenerated)
  - robots.txt                                   (regenerated)

Source of truth for content:
  - _content/commercial.json  (commercial + Cyprus pages, from Agent A)
  - _content/blog.json        (blog articles, from Agent B)

Source of truth for pages NOT generated by this script:
  - index.html                (the homepage — edited manually for full control)
  - sample-hotel.html, sample-restaurant.html
  - privacy.html, terms.html, gdpr.html, 404.html
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import re
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
CONTENT_DIR = BASE_DIR / "_content"
DOMAIN = "https://proinsights.com.cy"

# Cyprus-prefixed slugs go under /cyprus/
CYPRUS_PREFIX = "cyprus/"


# ---------------------------------------------------------------------------
# Shared HTML fragments
# ---------------------------------------------------------------------------

NAV_HTML = """
<header class="nav">
  <div class="nav-inner">
    <a href="/" class="brand">ProInsights.</a>
    <nav class="nav-links" id="navlinks">
      <div class="nav-dropdown">
        <button class="nav-drop-trigger" type="button" aria-haspopup="true" aria-expanded="false">For your business <span class="nav-drop-chevron">▾</span></button>
        <div class="nav-drop-menu" role="menu">
          <a href="/restaurant-review-management-software" role="menuitem">
            <span class="nav-drop-label">Daily review intelligence</span>
            <span class="nav-drop-desc">One email + one WhatsApp message every morning. Know what changed overnight.</span>
          </a>
          <a href="/ai-review-response-generator-restaurants" role="menuitem">
            <span class="nav-drop-label">AI-drafted replies</span>
            <span class="nav-drop-desc">Multilingual responses in your house voice. You review and post.</span>
          </a>
          <a href="/hotel-competitor-benchmarking" role="menuitem">
            <span class="nav-drop-label">Competitor tracking</span>
            <span class="nav-drop-desc">5-10 competitors monitored daily. See what they're doing differently.</span>
          </a>
          <a href="/guest-feedback-analytics" role="menuitem">
            <span class="nav-drop-label">Sentiment &amp; analytics</span>
            <span class="nav-drop-desc">By department, by source, by venue. Trends you can act on.</span>
          </a>
          <a href="/hotel-reputation-management-software" role="menuitem">
            <span class="nav-drop-label">Rate &amp; reputation benchmark</span>
            <span class="nav-drop-desc">Verified rate comparison and category positioning. Where do you really stand.</span>
          </a>
          <div class="nav-drop-sep"></div>
          <a href="/cyprus/" role="menuitem">
            <span class="nav-drop-label">For Cyprus 🇨🇾</span>
            <span class="nav-drop-desc">Locally built. Pages for Limassol, Nicosia, Paphos, Larnaca.</span>
          </a>
        </div>
      </div>
      <a href="/pricing">Pricing</a>
      <a href="/blog/">Resources</a>
      <a href="/#contact">Contact</a>
    </nav>
    <a href="https://app.proinsights.com.cy/login" class="nav-login">Log in</a>
    <a href="/#contact" class="nav-cta">Book a demo</a>
    <button class="nav-burger" id="burger" aria-label="Menu">≡</button>
  </div>
</header>
"""

FOOTER_HTML = """
<footer class="footer">
  <div class="footer-inner">
    <div>
      <p class="footer-brand">ProInsights.</p>
      <p class="footer-sub">Daily review intelligence for hospitality.<br>Built in Cyprus 🇨🇾 for European HORECA.</p>
    </div>
    <div>
      <h4>Restaurants</h4>
      <a href="/restaurant-review-management-software">Review management</a>
      <a href="/google-review-monitoring-restaurants">Google monitoring</a>
      <a href="/ai-review-response-generator-restaurants">AI reply generator</a>
      <a href="/cyprus/restaurant-review-management">For Cyprus</a>
    </div>
    <div>
      <h4>Hotels</h4>
      <a href="/hotel-reputation-management-software">Reputation management</a>
      <a href="/tripadvisor-review-monitoring-hotels">TripAdvisor monitoring</a>
      <a href="/hotel-competitor-benchmarking">Competitor benchmarking</a>
      <a href="/cyprus/hotel-reputation-management">For Cyprus</a>
    </div>
    <div>
      <h4>Company</h4>
      <a href="/pricing">Pricing</a>
      <a href="/reviewpro-alternative">ReviewPro alternative</a>
      <a href="/blog/">Blog</a>
      <a href="/#contact">Contact</a>
      <a href="/privacy.html">Privacy</a>
      <a href="/terms.html">Terms</a>
      <a href="/gdpr.html">GDPR</a>
    </div>
  </div>
  <div class="footer-base">© 2026 ProInsights · hello@proinsights.com.cy</div>
</footer>
<script>
  // Burger menu toggle
  var _burger = document.getElementById('burger');
  if (_burger) _burger.addEventListener('click', function () { document.getElementById('navlinks').classList.toggle('open'); });
  document.querySelectorAll('#navlinks a').forEach(function (a) {
    a.addEventListener('click', function () { document.getElementById('navlinks').classList.remove('open'); });
  });

  // Nav-dropdown: click toggles open class (mobile tap + a11y).
  document.querySelectorAll('.nav-dropdown').forEach(function (dd) {
    var trigger = dd.querySelector('.nav-drop-trigger');
    if (!trigger) return;
    trigger.addEventListener('click', function (e) {
      e.stopPropagation();
      var isOpen = dd.classList.toggle('open');
      trigger.setAttribute('aria-expanded', isOpen ? 'true' : 'false');
    });
  });
  // Close dropdowns when clicking outside
  document.addEventListener('click', function () {
    document.querySelectorAll('.nav-dropdown.open').forEach(function (dd) {
      dd.classList.remove('open');
      var trigger = dd.querySelector('.nav-drop-trigger');
      if (trigger) trigger.setAttribute('aria-expanded', 'false');
    });
  });
</script>
"""

# ---------------------------------------------------------------------------
# Page template
# ---------------------------------------------------------------------------

PAGE_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>{title}</title>
<meta name="description" content="{description}">
<meta name="theme-color" content="#FAF6F1">
<link rel="canonical" href="{canonical_url}">
<link rel="icon" type="image/png" href="https://raw.githubusercontent.com/conkyrlakis-hash/proinsights-brand-assets/main/proinsights-light-on-dark.png">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{description}">
<meta property="og:url" content="{canonical_url}">
<meta property="og:type" content="{og_type}">
<meta property="og:image" content="https://raw.githubusercontent.com/conkyrlakis-hash/proinsights-brand-assets/main/proinsights-light-on-dark.png">
<meta property="og:site_name" content="ProInsights">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{title}">
<meta name="twitter:description" content="{description}">
<meta name="twitter:image" content="https://raw.githubusercontent.com/conkyrlakis-hash/proinsights-brand-assets/main/proinsights-light-on-dark.png">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{css_href}">
<script type="application/ld+json">
{schema_json}
</script>
</head>
<body>
{nav_html}
{breadcrumb_html}
<main class="page">
{body_html}
</main>
{footer_html}
</body>
</html>
"""


# ---------------------------------------------------------------------------
# Schema helpers
# ---------------------------------------------------------------------------

def organization_schema():
    return {
        "@type": "Organization",
        "name": "ProInsights",
        "url": DOMAIN + "/",
        "logo": "https://raw.githubusercontent.com/conkyrlakis-hash/proinsights-brand-assets/main/proinsights-light-on-dark.png",
        "description": "AI review intelligence for restaurants and hotels — daily WhatsApp and email reports from Google, TripAdvisor and competitor reviews.",
        "founder": {"@type": "Person", "name": "Constantinos Kyrlakis"},
        "areaServed": ["CY", "GR", "DE", "EU"],
        "contactPoint": {
            "@type": "ContactPoint",
            "email": "hello@proinsights.com.cy",
            "contactType": "Sales",
            "availableLanguage": ["English", "Greek", "German"],
        },
    }


def website_schema():
    return {
        "@type": "WebSite",
        "name": "ProInsights",
        "url": DOMAIN + "/",
        "publisher": {"@id": DOMAIN + "/#organization"},
    }


def software_application_schema():
    return {
        "@type": "SoftwareApplication",
        "name": "ProInsights",
        "applicationCategory": "BusinessApplication",
        "applicationSubCategory": "Online Reputation Management",
        "operatingSystem": "Web",
        "description": "AI review intelligence for restaurants and hotels. Daily WhatsApp, email and dashboard reports across Google, TripAdvisor and competitor reviews.",
        "offers": [
            {"@type": "Offer", "name": "Hotel Basic", "price": "79", "priceCurrency": "EUR"},
            {"@type": "Offer", "name": "Hotel Advanced", "price": "139", "priceCurrency": "EUR"},
            {"@type": "Offer", "name": "Hotel Pro", "price": "189", "priceCurrency": "EUR"},
            {"@type": "Offer", "name": "Hotel Expert", "price": "249", "priceCurrency": "EUR"},
        ],
    }


def faq_schema(faq_list):
    if not faq_list:
        return None
    return {
        "@type": "FAQPage",
        "mainEntity": [
            {
                "@type": "Question",
                "name": item["q"],
                "acceptedAnswer": {"@type": "Answer", "text": item["a"]},
            }
            for item in faq_list
        ],
    }


def breadcrumb_schema(items):
    """items: list of (label, url) tuples"""
    return {
        "@type": "BreadcrumbList",
        "itemListElement": [
            {
                "@type": "ListItem",
                "position": i + 1,
                "name": label,
                "item": url if url.startswith("http") else (DOMAIN + url),
            }
            for i, (label, url) in enumerate(items)
        ],
    }


def article_schema(title, description, slug, publish_date, category):
    return {
        "@type": "Article",
        "headline": title,
        "description": description,
        "url": f"{DOMAIN}/blog/{slug}",
        "datePublished": publish_date,
        "dateModified": publish_date,
        "author": {"@type": "Organization", "name": "ProInsights"},
        "publisher": {"@type": "Organization", "name": "ProInsights",
                      "logo": {"@type": "ImageObject", "url": "https://raw.githubusercontent.com/conkyrlakis-hash/proinsights-brand-assets/main/proinsights-light-on-dark.png"}},
        "articleSection": category,
    }


def local_business_schema(city):
    return {
        "@type": "LocalBusiness",
        "name": f"ProInsights — {city}",
        "url": f"{DOMAIN}/cyprus/{('hotel-reputation-management' if 'hotel' in city.lower() else 'restaurant-review-management')}",
        "areaServed": city,
        "address": {"@type": "PostalAddress", "addressCountry": "CY"},
    }


def combine_schema(*items):
    """Combine multiple JSON-LD nodes into a @graph array."""
    valid = [i for i in items if i]
    return {"@context": "https://schema.org", "@graph": valid}


# ---------------------------------------------------------------------------
# Renderers
# ---------------------------------------------------------------------------

def build_breadcrumb_html(items):
    """Visible breadcrumb trail. items = list of (label, url) tuples."""
    if not items or len(items) < 2:
        return ""
    crumbs = []
    for i, (label, url) in enumerate(items):
        if i < len(items) - 1:
            crumbs.append(f'<a href="{url}">{label}</a>')
        else:
            crumbs.append(f'<span aria-current="page">{label}</span>')
    inner = " <span class=\"crumb-sep\">›</span> ".join(crumbs)
    return f'<nav class="breadcrumb" aria-label="Breadcrumb"><div class="breadcrumb-inner">{inner}</div></nav>'


def build_faq_html(faq_list):
    if not faq_list:
        return ""
    items = "\n".join(
        f'<details class="faq-item"><summary>{escape_html(item["q"])}</summary><div class="faq-answer">{item["a"]}</div></details>'
        for item in faq_list
    )
    return f"""
<section class="band band-white">
  <div class="band-inner band-narrow">
    <p class="section-tag">Frequently asked</p>
    <h2 class="h-big">Questions, answered.</h2>
    <div class="faq-list">{items}</div>
  </div>
</section>"""


def build_cta_section(headline=None, sub=None):
    h = headline or "Want to see what guests and competitors are saying tomorrow morning?"
    s = sub or "Pick a 15-minute slot. We hand you a working report from your venues by tomorrow morning."
    return f"""
<section class="band band-ink" id="cta">
  <div class="band-inner center">
    <h2 class="h-big light">{h}</h2>
    <p class="band-lead center light">{s}</p>
    <a href="/#contact" class="btn-light">Book a demo</a>
    <a href="/sample-restaurant.html" class="btn-ghost-light">See sample report</a>
  </div>
</section>"""


def render_commercial_page(slug, content, *, is_cyprus=False):
    """slug: page slug (no leading slash). content: dict from commercial.json."""
    title = content["title"]
    description = content["description"]
    h1 = content["h1"]
    intro = content.get("intro", "")
    body_html = content["body_html"]
    faq_list = content.get("faq", [])
    schema_type = content.get("schema_type", "WebPage")

    url_path = f"/{slug}" if not is_cyprus else f"/cyprus/{slug.replace('cyprus/', '')}"
    canonical_url = DOMAIN + url_path
    css_href = "../design-b.css" if is_cyprus else "design-b.css"

    # Breadcrumb
    if is_cyprus:
        breadcrumb_items = [("Home", "/"), ("Cyprus", "/cyprus/"), (h1.split("|")[0].strip()[:40], url_path)]
    else:
        breadcrumb_items = [("Home", "/"), (h1[:50], url_path)]

    # Schemas
    schema_nodes = [organization_schema(), website_schema()]
    if schema_type == "SoftwareApplication":
        schema_nodes.append(software_application_schema())
    if is_cyprus:
        city = "Cyprus hotels" if "hotel" in slug else "Cyprus restaurants"
        schema_nodes.append(local_business_schema(city))
    if faq_list:
        schema_nodes.append(faq_schema(faq_list))
    schema_nodes.append(breadcrumb_schema(breadcrumb_items))

    schema_json = json.dumps(combine_schema(*schema_nodes), indent=2)
    breadcrumb_html = build_breadcrumb_html(breadcrumb_items)

    # Compose body
    hero = f"""
<section class="hero hero-small">
  <div class="hero-inner narrow">
    <div class="hero-text">
      <h1>{h1}</h1>
      {intro}
      <a href="/#contact" class="btn-dark">Book a demo</a>
      <a href="/sample-restaurant.html" class="btn-ghost">See sample report</a>
    </div>
  </div>
</section>"""

    full_body = hero + body_html + build_faq_html(faq_list) + build_cta_section()

    return PAGE_TEMPLATE.format(
        title=title,
        description=description,
        canonical_url=canonical_url,
        og_type="website",
        css_href=css_href,
        schema_json=schema_json,
        nav_html=NAV_HTML,
        breadcrumb_html=breadcrumb_html,
        body_html=full_body,
        footer_html=FOOTER_HTML,
    )


def render_blog_article(slug, article):
    title = article["title"]
    description = article["description"]
    h1 = article["h1"]
    body_html = article["body_html"]
    faq_list = article.get("faq", [])
    publish_date = article.get("publish_date", str(dt.date.today()))
    category = article.get("category", "Hospitality guides")
    read_time = article.get("read_time_min", 6)

    url_path = f"/blog/{slug}"
    canonical_url = DOMAIN + url_path
    css_href = "../design-b.css"

    breadcrumb_items = [("Home", "/"), ("Blog", "/blog/"), (title[:50], url_path)]

    schema_nodes = [
        organization_schema(),
        article_schema(title, description, slug, publish_date, category),
        breadcrumb_schema(breadcrumb_items),
    ]
    if faq_list:
        schema_nodes.append(faq_schema(faq_list))
    schema_json = json.dumps(combine_schema(*schema_nodes), indent=2)
    breadcrumb_html = build_breadcrumb_html(breadcrumb_items)

    article_html = f"""
<section class="band band-white">
  <div class="band-inner band-narrow">
    <p class="post-meta"><span class="post-cat">{category}</span> · <time datetime="{publish_date}">{publish_date}</time> · {read_time} min read</p>
    <h1 class="post-h1">{h1}</h1>
    <div class="prose">{body_html}</div>
  </div>
</section>"""

    full_body = article_html + build_faq_html(faq_list) + build_cta_section(
        headline="Want this kind of intelligence on your reviews every morning?",
        sub="ProInsights does this work for you, in one email and one WhatsApp message a day.",
    )

    return PAGE_TEMPLATE.format(
        title=title,
        description=description,
        canonical_url=canonical_url,
        og_type="article",
        css_href=css_href,
        schema_json=schema_json,
        nav_html=NAV_HTML,
        breadcrumb_html=breadcrumb_html,
        body_html=full_body,
        footer_html=FOOTER_HTML,
    )


def render_blog_index(articles):
    cards = []
    for slug, art in sorted(articles.items(), key=lambda kv: kv[1].get("publish_date", ""), reverse=True):
        pub = art.get("publish_date", "")
        category = art.get("category", "")
        read_time = art.get("read_time_min", 6)
        cards.append(f"""
<a class="blog-card" href="/blog/{slug}">
  <p class="post-meta"><span class="post-cat">{category}</span> · {read_time} min</p>
  <h3>{art['title']}</h3>
  <p class="blog-desc">{art['description']}</p>
  <time datetime="{pub}">{pub}</time>
</a>""")

    body = f"""
<section class="hero hero-small">
  <div class="hero-inner narrow">
    <div class="hero-text">
      <h1>The ProInsights blog</h1>
      <p class="hero-stand">Practical guides for restaurants and hotels on reviews, reputation, and competitor signal — written for managers, not marketing teams.</p>
    </div>
  </div>
</section>
<section class="band band-white">
  <div class="band-inner">
    <div class="blog-grid">{"".join(cards)}</div>
  </div>
</section>"""

    breadcrumb_items = [("Home", "/"), ("Blog", "/blog/")]
    schema_nodes = [
        organization_schema(),
        website_schema(),
        breadcrumb_schema(breadcrumb_items),
    ]
    schema_json = json.dumps(combine_schema(*schema_nodes), indent=2)
    breadcrumb_html = build_breadcrumb_html(breadcrumb_items)

    return PAGE_TEMPLATE.format(
        title="Blog | ProInsights — practical guides for restaurants and hotels",
        description="Practical guides on review management, reputation, sentiment analysis, and competitor tracking for restaurant and hotel operators.",
        canonical_url=DOMAIN + "/blog/",
        og_type="website",
        css_href="../design-b.css",
        schema_json=schema_json,
        nav_html=NAV_HTML,
        breadcrumb_html=breadcrumb_html,
        body_html=body,
        footer_html=FOOTER_HTML,
    )


def render_cyprus_index():
    """Index page at /cyprus/ pointing to the two main local pages."""
    breadcrumb_items = [("Home", "/"), ("Cyprus", "/cyprus/")]
    body = """
<section class="hero hero-small">
  <div class="hero-inner narrow">
    <div class="hero-text">
      <h1>ProInsights for Cyprus hospitality</h1>
      <p class="hero-stand">Daily review intelligence for restaurants, hotels and HORECA groups across Limassol, Nicosia, Larnaca, Paphos, Ayia Napa and Protaras. Built locally — sold across the EU.</p>
      <a href="/#contact" class="btn-dark">Book a demo</a>
    </div>
  </div>
</section>
<section class="band band-white">
  <div class="band-inner">
    <div class="three-cards">
      <a class="why-card linkable" href="/cyprus/restaurant-review-management">
        <h3>For Cyprus restaurants</h3>
        <p>Daily Google + TripAdvisor review intelligence, dish + staff mentions, competitor tracking for Cypriot restaurants and bistros.</p>
        <span class="resource-cta">View page →</span>
      </a>
      <a class="why-card linkable" href="/cyprus/hotel-reputation-management">
        <h3>For Cyprus hotels</h3>
        <p>Department-level sentiment, competitor benchmarking, verified rate comparison for Cyprus 3★–5★ hotels and resorts.</p>
        <span class="resource-cta">View page →</span>
      </a>
    </div>
  </div>
</section>"""

    schema_nodes = [
        organization_schema(),
        local_business_schema("Cyprus"),
        breadcrumb_schema(breadcrumb_items),
    ]
    schema_json = json.dumps(combine_schema(*schema_nodes), indent=2)

    return PAGE_TEMPLATE.format(
        title="ProInsights Cyprus | Review management for hotels & restaurants",
        description="Cyprus-built review intelligence for hospitality operators in Limassol, Nicosia, Larnaca, Paphos, Ayia Napa and Protaras.",
        canonical_url=DOMAIN + "/cyprus/",
        og_type="website",
        css_href="../design-b.css",
        schema_json=schema_json,
        nav_html=NAV_HTML,
        breadcrumb_html=build_breadcrumb_html(breadcrumb_items),
        body_html=body,
        footer_html=FOOTER_HTML,
    )


# ---------------------------------------------------------------------------
# Sitemap + robots
# ---------------------------------------------------------------------------

def write_sitemap(commercial_slugs, blog_slugs, cyprus_slugs, output):
    today = dt.date.today().isoformat()
    urls = []
    # Homepage
    urls.append(("/", "1.0", "weekly"))
    # Commercial pages
    for s in commercial_slugs:
        urls.append((f"/{s}", "0.9", "monthly"))
    # Cyprus pages
    urls.append(("/cyprus/", "0.8", "monthly"))
    for s in cyprus_slugs:
        urls.append((f"/cyprus/{s}", "0.8", "monthly"))
    # Blog
    urls.append(("/blog/", "0.7", "weekly"))
    for s in blog_slugs:
        urls.append((f"/blog/{s}", "0.6", "monthly"))
    # Pricing already in commercial_slugs
    body = "\n".join(
        f'  <url>\n    <loc>{DOMAIN}{u}</loc>\n    <lastmod>{today}</lastmod>\n    <changefreq>{freq}</changefreq>\n    <priority>{pri}</priority>\n  </url>'
        for u, pri, freq in urls
    )
    xml = f'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n{body}\n</urlset>\n'
    output.write_text(xml, encoding="utf-8")


def write_robots(output):
    body = (
        "User-agent: *\n"
        "Allow: /\n"
        "Disallow: /sample-hotel.html\n"
        "Disallow: /sample-restaurant.html\n"
        "Disallow: /_content/\n"
        "\n"
        f"Sitemap: {DOMAIN}/sitemap.xml\n"
    )
    output.write_text(body, encoding="utf-8")


# ---------------------------------------------------------------------------
# Misc utils
# ---------------------------------------------------------------------------

def escape_html(s):
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
              .replace('"', "&quot;").replace("'", "&#39;"))


def slug_is_cyprus(slug):
    return slug.startswith("cyprus/")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description="Build the ProInsights SEO site.")
    ap.add_argument("--check", action="store_true", help="Validate content files, don't write")
    args = ap.parse_args()

    commercial_path = CONTENT_DIR / "commercial.json"
    blog_path = CONTENT_DIR / "blog.json"
    fallback_commercial_path = CONTENT_DIR / "fallback_commercial.json"
    fallback_blog_path = CONTENT_DIR / "fallback_blog.json"

    # Start from fallback (hand-written, always present) then overlay agent
    # content (richer, may be missing).
    commercial = {}
    if fallback_commercial_path.exists():
        commercial.update(json.loads(fallback_commercial_path.read_text(encoding="utf-8")))
    if commercial_path.exists():
        agent_content = json.loads(commercial_path.read_text(encoding="utf-8"))
        commercial.update(agent_content)
        print(f"  loaded agent commercial.json: {len(agent_content)} pages (override-merged)")
    else:
        print(f"⚠ {commercial_path.name} not present — using fallback only.")

    blog = {}
    if fallback_blog_path.exists():
        blog.update(json.loads(fallback_blog_path.read_text(encoding="utf-8")))
    if blog_path.exists():
        agent_blog = json.loads(blog_path.read_text(encoding="utf-8"))
        blog.update(agent_blog)
        print(f"  loaded agent blog.json: {len(agent_blog)} articles (override-merged)")
    else:
        print(f"⚠ {blog_path.name} not present — using fallback only.")

    print(f"Total: {len(commercial)} commercial pages, {len(blog)} blog articles.")

    if args.check:
        for slug, page in commercial.items():
            required = ["title", "description", "h1", "body_html"]
            missing = [k for k in required if k not in page or not page[k]]
            if missing:
                print(f"  ⚠ commercial['{slug}'] missing: {missing}")
        for slug, art in blog.items():
            required = ["title", "description", "h1", "body_html"]
            missing = [k for k in required if k not in art or not art[k]]
            if missing:
                print(f"  ⚠ blog['{slug}'] missing: {missing}")
        return

    # --- Commercial + Cyprus pages -------------------------------------------
    commercial_slugs = []
    cyprus_slugs = []
    for slug, content in commercial.items():
        is_cyprus = slug_is_cyprus(slug)
        html = render_commercial_page(slug, content, is_cyprus=is_cyprus)
        if is_cyprus:
            sub = slug.replace("cyprus/", "")
            out_path = BASE_DIR / "cyprus" / f"{sub}.html"
            cyprus_slugs.append(sub)
        else:
            out_path = BASE_DIR / f"{slug}.html"
            commercial_slugs.append(slug)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(html, encoding="utf-8")
        print(f"  wrote {out_path.relative_to(BASE_DIR)} ({len(html):,} bytes)")

    # Cyprus index
    if cyprus_slugs:
        cyprus_index_html = render_cyprus_index()
        (BASE_DIR / "cyprus" / "index.html").write_text(cyprus_index_html, encoding="utf-8")
        print(f"  wrote cyprus/index.html ({len(cyprus_index_html):,} bytes)")

    # --- Blog ----------------------------------------------------------------
    blog_slugs = []
    for slug, article in blog.items():
        html = render_blog_article(slug, article)
        out_path = BASE_DIR / "blog" / f"{slug}.html"
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(html, encoding="utf-8")
        blog_slugs.append(slug)
        print(f"  wrote {out_path.relative_to(BASE_DIR)} ({len(html):,} bytes)")

    # Blog index
    if blog:
        blog_idx_html = render_blog_index(blog)
        (BASE_DIR / "blog" / "index.html").write_text(blog_idx_html, encoding="utf-8")
        print(f"  wrote blog/index.html ({len(blog_idx_html):,} bytes)")

    # --- Sitemap + robots ----------------------------------------------------
    write_sitemap(commercial_slugs, blog_slugs, cyprus_slugs, BASE_DIR / "sitemap.xml")
    print(f"  wrote sitemap.xml ({len(commercial_slugs)} commercial + {len(cyprus_slugs)} cyprus + {len(blog_slugs)} blog URLs)")
    write_robots(BASE_DIR / "robots.txt")
    print("  wrote robots.txt")

    print(f"\nDone. {len(commercial_slugs) + len(cyprus_slugs) + len(blog_slugs) + 1} pages generated.")
    print(f"\nNext: open {BASE_DIR / 'index.html'} in a browser to verify.")


if __name__ == "__main__":
    main()
